### ISSUE TITLE
c pa tré la sékurité

### ISSUE THREAD

**Issue by notAutomne** [KaisenCAS/kaisenlinux#1]
![](https://i.imgur.com/c83jwme.png)

Faut pas oublier d'effacer son fichier key4.db et cookies.sqlite :)

**Comment by kevinchevreuil** [comment]
C'est un profil Firefox par défaut qui ne contient aucun mot de passe ou informations personnelles, des extensions ont été ajoutées, d'où l'origine de ces fichiers. 
Donc "c pa tré la sékurité".....

**Comment by notAutomne** [comment]
Oui, j'avais bien compris mais ça serait nettement plus propre d'utiliser un profil fraîchement générer en CLI:

https://developer.mozilla.org/fr/docs/Mozilla/Command_Line_Options

Puis d'import les extensions
________________________________

**Comment by ghost** [comment]
"c pa tré la sékurité" , tu es donc expert en sécurité ? Tu a discord ?

**Comment by notAutomne** [comment]
@Eawhitehat Je ne me qualifie pas d'expert en sécurité. Très (très) peu de personne ont ce niveau et je n'en fait clairement pas parti. 
Cependant j'ai un niveau suffisant pour repérer les bad practices et savoir pourquoi elle sont mauvaises.
Mon discord: Automne#2039
