### ISSUE TITLE
Language Selection

### ISSUE THREAD

**Issue by defactocth** [KaisenCAS/kaisenlinux#2]
Hi,

I would like to give this tool a try but I cannot see an easy way to change the language to English.

I think I found a language list stumbling around in the menus but there was not an option for English in the list.

Any help would be most appreciated thanks (preferably with pictures as I cannot read French).

**Comment by kevinchevreuil** [comment]
Hello, 

Thank you for your interest in Kaisen Linux !

The beta version has live in English. Installation in English is still possible and the menus in the OS are translated into English, regardless of the version used (on version 20191229, you can install it in English, but the live is in French, for that I refer you to the current beta which fixes this major problem).
The official website: https://kaisen-linux.org will soon be translated into English and will provide support for English and French.

The link to download the most updated version in beta (some bugs are fixed, but the distribution remains usable for its initial function, that is to say system maintenance), it is here:
https://iso.kaisen-linux.org/beta/kaisenlinux20200114-amd64.iso

This beta unlike the last stable version (version 20191229), brings the possibility of booting on the live directly with the language and the keyboard in English, as well as the support of UEFI (installation in UEFI is not still well taken care of and temporary fixes are proposed, even if the option is available, but you can always use the live for your maintenance operations).
In this version, some bugs of the old stable version have been fixed.
Live password is: kaisen
The password only works on beta (on version 20191229, the password being absent and the user had to define it himself).

Here is the changelog of the translated beta and the only bug it has:

Version 20200114 (BETA VERSION, unable to install GRUB on UEFI during installation but solution given on the downloads page):

General:

- Addition of the Guymager tool
- Startup support on UEFI
- Creation of the "base-files-kaisen" package
- Deletion of the file / usr / lib / os-variant and its symlink / etc / os-variant (replaced by the base-files-kaisen package)
- Redesign of ISO menus
- Version stamped 20200114 as well as the code name "impossible"
- Removal of the clamav daemon to relieve system resources (tool still present)
- Deletion of the modified lsb_release.py file (replaced by the base-files-kaisen package)
- Installation of rtl and iwl firmware to support certain Realtek and Intel Wi-Fi drivers
- Addition of contrib and non-free repositories in sources.list
- Change of default deposit to http://deb.debian.org/debian/ (replaces http: //ftp.fr.debian/org/debian)

Live:

- Addition of USB persistence (keep your data during a live session)
- Addition of encrypted persistence (encryption of persistent data)
- Addition of the possibility to fully load your system in RAM (8GB RAM minimum)
- Adding English in addition to French
- Default password for the live: kaisen (replaces the blank password which prevented the session from being unlocked when the station was locked or put on standby live)

Installer:

- Addition of the installer in expert and rescue mode
- Disable network configuration (everything is contained in ISO and can be installed offline)
- Deactivation of missing firmware message
- Modification of the installer to deactivate the network configuration
- Default post name on kaisenlinux
- No possibility to create root password during installation
- Automatic restart at the end of installation.

**Comment by kevinchevreuil** [comment]
If you need help with installation, use, or any other question, you can contact me **support@kaisen-linux.org**
I will get back to you as soon as possible.
I want to clarify that Kaisen Linux is a community project that I maintain in my spare time :)
I may not necessarily answer the same day, but I will necessarily answer you :)
We look forward to counting you among Kaisen Linux users!

**Comment by defactocth** [comment]
Hi,

Thanks for the prompt and detailed reply.
I was able to use the beta image without issue.

Thanks very much for the advice.
I found the tool very useful for diagnosing an issue with a SSD.

Look forward to following this distribution and seeing how it develops.
